[project]
name = "media-rs"
version = "0.1.0"
description = "Application to recommend different media"
authors = [
    {name = "Mitchell Bird",email = "mitchell.bird@live.co.uk"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest (>=9.0.2,<10.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "pandas (>=2.3.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
